#!/usr/bin/env bash

# Get website passwords from a secrets manager.

set -euo pipefail

username_only=0
password_only=0

while getopts ":uph" option; do
    case $option in
    u) username_only=1 ;;
    p) password_only=1 ;;
    :)
        printf "Option missing argument: %s\n" "$OPTARG" >&2
        exit 1
        ;;
    *)
        printf "Invalid option: %s\n" "$OPTARG" >&2
        exit 1
        ;;
    esac
done && shift $((OPTIND - 1))

qute_command() {
    printf "%s\n" "$*" >"$QUTE_FIFO"
}

fake_key() {
    qute_command "fake-key" "$1"
}

fake_key_raw() {
    local i text=$1
    for ((i = 0; i < ${#text}; i++)); do
        c=${text:$i:1}
        if [[ $c == " " ]]; then
            fake_key '" "'
        else
            fake_key "\\$c"
        fi
    done
}

domain=${QUTE_URL#*://}
domain=${domain%%/*}

filters=()
while [[ $domain == *.* ]]; do
    filters+=("$domain")
    domain=${domain#*.}
done

if ! entry=$(bemenu-secrets -P websites -p login choose "${filters[@]}" | head -n2) || [[ -z $entry ]]; then
    printf "Unable to choose a secret: %s\n" "${filters[*]}" >&2
    exit 1
fi

name=${entry%%$'\n'*}
password=${entry##*$'\n'}
username=${name##*/}

if ((username_only)); then
    fake_key_raw "$username"
elif ((password_only)); then
    fake_key_raw "$password"
else
    fake_key_raw "$username"
    fake_key "<Tab>"
    fake_key_raw "$password"
fi

qute_command "mode-enter insert"
