#!/usr/bin/env bash

set -eu

readarray -t files

case $1 in
"Delete") trash "${files[@]}" ;;
"C-w") setbg "${files[0]}" ;;
"C-c") realpath "${files[@]}" | xsel -ib ;;
"C-e") gimp -ad "${files[@]}" ;;
"C-p") krita "${files[@]}" ;;
"C-r")
    for file in "${files[@]}"; do
        convert -rotate 90 "$file" "$file"
    done
    ;;
esac
