#!/usr/bin/env bash

set -eu

# Needed to change screen brightness.
sudo gpasswd -a "$USER" video

sudo gpasswd -a "$USER" locate
sudo updatedb

sudo chsh -s /bin/zsh "$USER"

systemctl --user enable swayidle.service
systemctl --user enable mako.service
systemctl --user enable udiskie.service
systemctl --user enable sway-setbg.service
systemctl --user enable notify-battery.timer
