#!/usr/bin/env bash

set -eu

# Needed to change screen brightness.
sudo gpasswd --add "$USER" video

sudo gpasswd --add "$USER" locate
sudo updatedb

sudo chsh --shell /bin/zsh "$USER"

systemctl --user enable mako.service
systemctl --user enable udiskie.service
systemctl --user enable swayidle.service

if [[ -e /sys/class/power_supply/BAT0 ]] ; then
    systemctl --user enable notify-battery.timer
fi
