order = [
    "hostname",
    "network_interfaces",
    "path_exists:mullvad",
    "systemd_unit:swayidle",
    "mounts",
    "cpu_usage",
    "memory_info",
    "batteries",
    "mpris",
    "pulseaudio",
    "clock"
]

[settings.network_interfaces]
on_click.1 = 'terminal --hold -e networkctl status'
on_click.2 = 'terminal -e sudo iftop -i ${instance}'
on_click.3 = 'terminal -e ip -color -human monitor'

[settings.mounts]
on_click.1 = 'terminal --hold -e df --si --human-readable ${instance}'
on_click.3 = 'terminal -e ncdu ${instance}'

[settings."path_exists:mullvad"]
path = "/sys/class/net/wg-mullvad"
label = "vpn"
on_click.1 = "mullvad-toggle"
on_click.2 = 'terminal -e sudo iftop -i wg-mullvad'
on_click.3 = "terminal --hold -e mullvad-details"

[settings."systemd_unit:swayidle"]
label = "idle"
unit = "swayidle.service"
user = true

[settings.clock]
on_click.1 = "date --iso-8601=seconds | wl-copy -n"
on_click.2 = "date --iso-8601=seconds --utc | wl-copy -n"
on_click.3 = "terminal -e set-timezone"

[settings.cpu_usage]
on_click.1 = "terminal -e top"
on_click.3 = "terminal -e sudo iotop"

[settings.memory_info]
on_click.1 = "terminal -e watch free -h"

[settings.batteries]
on_click.1 = "terminal -e watch acpi --details"

[settings.pulseaudio]
on_click.1 = "set-audio-volume mute"
on_click.3 = "pavucontrol"
on_click.4 = "set-audio-volume up"
on_click.5 = "set-audio-volume down"

[settings.mpris]
on_click.1 = "playerctl play-pause"
on_click.3 = "terminal --hold -e playerctl metadata"
