#!/usr/bin/env bash

# Configure the Mullvad VPN to limit relay selection to a location.
# Usage: mullvad-set-location COUNTRY [CITY]

set -euo pipefail

relays_file=/usr/local/share/mullvad/relays.json

country=${1:?missing country code}

readarray -t countries < <(jq -r '.countries[].code' "$relays_file" | sort)

if ! printf "%s\n" "${countries[@]}" | grep -q "^$country$"; then
    printf "Invalid country code: %s\n" "$country" >&2
    printf "Recognized country codes: %s\n" "${countries[*]}" >&2
    exit 1
fi

city=${2:-}

readarray -t cities < <(jq -r --arg country "$country" '.countries[] | select(.code == $country).cities[].code' "$relays_file" | sort)

if [[ -n $city ]] && ! printf "%s\n" "${cities[@]}" | grep -q "^$city$"; then
    printf "Invalid city code: %s\n" "$city" >&2
    printf "Recognized city codes for %s: %s\n" "$country" "${cities[*]}" >&2
    exit 1
fi

config_file=/usr/local/etc/mullvad/location.conf

mkdir -p "$(dirname "$config_file")"

entries=(COUNTRY "$country")
if [[ -n $city ]]; then
    entries+=(CITY "$city")
fi

printf "%s=%s\n" "${entries[@]}" >"$config_file"
