#!/usr/bin/env bash

# Configure the Mullvad VPN forwarded port.
# Usage: mullvad-set-port PORT

# Be sure to set up port forwarding here:
# https://mullvad.net/en/account/#/port-forwarding

set -euo pipefail

port_config_file=/usr/local/etc/mullvad/port.conf

port=${1:?missing port number}

if [[ ! $port =~ ^[0-9]+$ ]] || ((port < 0 || port >65535)); then
    printf "Invalid port: %s (must be a number between 0-65535)\n" "$port" >&2
    exit 1
fi

mkdir -p "$(dirname "$port_config_file")"

printf "PORT=%d\n" "$port" >"$port_config_file"
