#!/usr/bin/env bash

set -euo pipefail

port_config_file=/usr/local/etc/mullvad/port.conf

[[ -f $port_config_file ]] || exit 0

unset PORT

if ! . "$port_config_file"; then
    printf "Unable to source file: %q\n" "$port_config_file" >&2
    exit 1
fi

if [[ ! -v PORT || -z $PORT ]]; then
    printf "Variable is unset or empty: %s\n" PORT >&2
    exit 1
fi

for protocol in udp tcp; do
    nftables-close-port "$protocol" "$PORT"
done
